void test_maxRotateFunction();
void test_calcEquation();
void test_decodeString();
void test_decodeStringMy();
void test_nextPermutation();
void test_minimumTotal();
void test_countingBits();
void test_findItinerary();
void test_wiggleSort2();
void test_longestIncreasingPath();
void test_isValidSerialization();
void test_grayCode();
void test_recoverTree();
void test_LRUCache();
void test_oddEvenList();
void test_lengthOfLIS();
void test_numTrees();
void test_getNPrimes();
void test_coinChange();
void test_maxProductOfWordLen();
void test_groupAnagrams();
void test_removeInvalidParentheses();
void test_removeDuplicateLetters();
void test_FindReverseBstKth4();
void test_FindReverseBstKth3();
void test_FindReverseBstKth2();
void test_FindReverseBstKth1();
void testPalidromePartitioning();
void test_reverseWordsInString();
void test_FindMedianFromDataStream();
void test_SerializeDeserializeBT();
void test_SerializeDeserializeBST();
void test_combinationSum2();
void test_subsetsWithDup();
void test_wordPattern();

int main(int /* argc */, const char * /* argv */ [])
{
    test_maxRotateFunction();
    test_calcEquation();
    test_decodeString();
    test_decodeStringMy();
    test_nextPermutation();
    test_minimumTotal();
    test_countingBits();
    test_findItinerary();
    test_wiggleSort2();
    test_longestIncreasingPath();
    test_isValidSerialization();
    test_grayCode();
    test_recoverTree();
    test_LRUCache();
    test_oddEvenList();
    test_lengthOfLIS();
    test_numTrees();
    test_getNPrimes();
    test_coinChange();
    test_maxProductOfWordLen();
    test_groupAnagrams();
    test_removeInvalidParentheses();
    test_removeDuplicateLetters();
    test_FindReverseBstKth4();
    test_FindReverseBstKth3();
    test_FindReverseBstKth2();
    test_FindReverseBstKth1();
    testPalidromePartitioning();
    test_reverseWordsInString();
    test_FindMedianFromDataStream();
    test_SerializeDeserializeBST();
    test_SerializeDeserializeBT();
    test_combinationSum2();
    test_subsetsWithDup();
    test_wordPattern();
    return 0;
}
